# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  from = "/api"
  to = "https://kanban-rest-rss.herokuapp.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "*"
